Change to use _json_data instead of _json. Resolves #3.
Fixes "AttributeError: 'Person' object has no attribute '_json' #3"

Reading through the source code of the ciscosparkapi module it seems
that at some point (I didn't dig for when) `_json` became `_json_data`.
This patch changes `CiscoSpark.py` to use the new name.